### ISSUE TITLE
Not Injecting into Existing Saves

### ISSUE THREAD

**Issue by The-Tarkol** [touchfluffytails/Palworld-Palbox-Slot-Injector#4]
Hello! I got to the point where the prompt had said it successfully injected into all 4 players. I then converted the json back to .sav, started up the server, and....the palboxes did not change at all. Am I missing a step somewhere?

I'd be happy to provide any files or anything else to be of assistance. The fastest way to reach me is probably Discord (Tarkol), but I'll try and reply here as well.

**Comment by touchfluffytails** [comment]
Did you make sure to setup "Bigger and Reorganized PalBox"? You need it and to have it's .lua set to the same values you injected into the save.  In terms of discord, the official pocketpair discord has a palworld modding channel you can go into to get assistance I believe.

**Comment by The-Tarkol** [comment]
Yes I had that mod installed, when I created a new game it loaded up with the bigger palbox. I did notice the level.sav.json is about half the size after attempting to inject the palbox change, so something's definitely up

**Comment by touchfluffytails** [comment]
The size difference is actually fine. Mine is minifying the json file (removing extra spaces and new lines not needed for the data and is for users reading the file) while by default save-tools doesn't minify. It outputs half the size because have the size is just newlines and spaces to make it user readable 😂.

Are you trying to run it on a dedicated server? I haven't personally ran it on one yet but I have a bit of a guide on the nexus thats more fleshed currently than githubs that is based on someone elses comments in another issue here.

**Comment by The-Tarkol** [comment]
Yeah I'm trying to run it on a dedicated server - all other mods appear to be working as intended. Is there somewhere in the level.sav.json I can check to validate the palboxes were injected properly?

**Comment by The-Tarkol** [comment]
So as it turns out, the palboxes are actually expanded - the merchant inventory shows the big box, and we can definitely add more pals than we're able to see. They just don't show as having extra space in the GUI. I'll look into reinstalling the bigger palbox mod and see if that fixes.

**Comment by The-Tarkol** [comment]
After updating the "Bigger Palbox" mod, all is well. Thanks!
